services:
  postgres:
    image: postgres:16
    container_name: postgres_sicooperative
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sicooperative
    ports:
      - "5432:5432"
